name: Release
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # This workflow contains a single job called "build"
  preform_release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
